# Generated by Django 5.1.7 on 2025-03-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejestrator',
            old_name='imie',
            new_name='osoba_kontaktowa',
        ),
        migrations.RemoveField(
            model_name='realizacja',
            name='czynnosc',
        ),
        migrations.RemoveField(
            model_name='realizacja',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='rejestrator',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='realizacja',
            name='grupa_spraw',
            field=models.CharField(default='C1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realizacja',
            name='numer_umowy',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realizacja',
            name='rejestrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rej_app.rejestrator'),
        ),
        migrations.AddField(
            model_name='realizacja',
            name='rodzaj_sprawy',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='adres',
            field=models.CharField(default='Default', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='numer_rejestracyjny',
            field=models.CharField(default='Default', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='rejestrator',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
