# Generated by Django 5.1.7 on 2025-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejestrator',
            old_name='imie',
            new_name='imie_nazwisko',
        ),
        migrations.RenameField(
            model_name='rejestrator',
            old_name='nazwisko',
            new_name='nazwa_firmy',
        ),
        migrations.AddField(
            model_name='rejestrator',
            name='adres',
            field=models.CharField(default='brak', max_length=300),
            preserve_default=False,
        ),
    ]
