# Generated by Django 5.1.7 on 2025-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0002_rename_imie_rejestrator_osoba_kontaktowa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacja',
            name='grupa_spraw',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='realizacja',
            name='numer_rejestracyjny',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rejestrator',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rejestrator',
            name='numer_rejestracyjny',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rejestrator',
            name='telefon',
            field=models.CharField(max_length=100),
        ),
    ]
