# Generated by Django 5.1.7 on 2025-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0002_rename_imie_rejestrator_imie_nazwisko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejestrator',
            name='numer_rejestracyjny',
            field=models.CharField(default='brak', max_length=5),
            preserve_default=False,
        ),
    ]
