# Generated by Django 5.1.7 on 2025-04-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0003_alter_realizacja_grupa_spraw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejestrator',
            old_name='osoba_kontaktowa',
            new_name='miasto',
        ),
    ]
