# Generated by Django 5.1.7 on 2025-03-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0003_rejestrator_numer_rejestracyjny'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizacja',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rej_app.rejestrator'),
        ),
    ]
