# Generated by Django 5.1.7 on 2025-04-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rej_app', '0004_rename_osoba_kontaktowa_rejestrator_miasto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realizacja',
            unique_together={('numer_rejestracyjny', 'rejestrator', 'rodzaj_sprawy')},
        ),
    ]
